import { Link } from "react-router-dom";
import Icon from "../Icon/Icon";
import { siteConfig } from "../../data/siteConfig";
import "./Hero.css";

/*
 * ---------------------------------------------------------------
 * THE HERO VISUAL  →  public/hero-stack.png
 * ---------------------------------------------------------------
 * TO SWAP THE IMAGE: overwrite  public/hero-stack.png  with your own
 * render. That is the whole procedure — no code change needed. Hard
 * refresh the browser (Ctrl+Shift+R) to bypass the cache.
 *
 * Any aspect ratio fits: the figure is sized by max-width with
 * height:auto. If your file is not 1200×1000, update the width/height
 * attributes below to match — they only exist to reserve space while
 * the image loads, so the page does not jump.
 *
 * The current file is a stand-in generated by
 * scripts/generate-hero-stack.mjs. It carries no text on purpose, so
 * nothing inside it can become unreadable at small sizes.
 *
 * Keep the legend below either way. It names the three layers in real
 * HTML — legible on a phone, editable without touching the artwork.
 * ---------------------------------------------------------------
 */

const assurances = [
  "Production-first delivery",
  "Your code, your infrastructure",
  "Measured against a real baseline",
];

/*
 * Industry labels drawn OVER the diagram as real HTML — not baked into the
 * image. They stay crisp at any zoom, are editable here, and can be hidden
 * on narrow screens where they would collide.
 *
 * `left` / `top` are percentages of the image box, matched to the tower
 * positions in scripts/generate-hero-stack.mjs. Each label is anchored by
 * its bottom-centre, so it sits just above its tower.
 *
 * IF YOU SWAP IN ARTWORK THAT ALREADY HAS ITS OWN LABELS: set
 * SHOW_TOWER_LABELS to false. Otherwise re-measure the percentages against
 * your image.
 */
const SHOW_TOWER_LABELS = true;

const towerLabels = [
  { id: "retail", label: "Retail", left: 21.3, top: 14.6 },
  { id: "finance", label: "Finance", left: 32.8, top: 5.4 },
  { id: "insurance", label: "Insurance", left: 44.3, top: 17.8 },
  { id: "logistics", label: "Logistics", left: 55.8, top: 1.8 },
  { id: "healthcare", label: "Healthcare", left: 67.3, top: 11.4 },
  { id: "saas", label: "SaaS", left: 78.7, top: 8.6 },
];

const legend = [
  {
    id: "apps",
    swatch: "app",
    title: "Industry applications",
    text: "Finance, insurance, healthcare, retail, logistics, SaaS",
  },
  {
    id: "core",
    swatch: "core",
    title: "The Foxtheta layer",
    text: "Retrieval, tools, guardrails and evaluation — where projects succeed or fail",
  },
  {
    id: "models",
    swatch: "base",
    title: "Foundation models",
    text: "Benchmarked per task and interchangeable — you are never locked in",
  },
];

export default function Hero() {
  return (
    <section className="hero">
      {/* decorative background layers */}
      <div className="hero__rays" aria-hidden="true" />
      <div className="hero__grid" aria-hidden="true" />
      <div className="hero__orb hero__orb--one" aria-hidden="true" />
      <div className="hero__orb hero__orb--two" aria-hidden="true" />

      <div className="container hero__inner">
        <div className="hero__copy">
          <span className="eyebrow eyebrow--pill">
            <span className="eyebrow__dot" aria-hidden="true" />
            {siteConfig.slogan}
          </span>

          <h1 className="hero__title">
            AI That Works Where Your{" "}
            <span className="text-gradient">Business Actually Runs</span>
          </h1>

          <p className="hero__lead">
            Foxtheta designs, builds and ships AI agents, knowledge systems and
            automation into live operations — with the evaluations, guardrails
            and audit trails that make them safe to depend on.
          </p>

          <ul className="hero__assurances">
            {assurances.map((item) => (
              <li key={item}>
                <Icon name="check" size={16} />
                {item}
              </li>
            ))}
          </ul>

          <div className="hero__actions">
            <Link to="/contact" className="btn btn--primary btn--lg">
              Get in Touch
              <Icon name="arrow" size={19} className="icon--arrow" />
            </Link>
            <Link to="/services" className="btn btn--outline btn--lg">
              Explore Services
            </Link>
          </div>
        </div>

        <figure className="hero__figure">
          <div className="hero__visual">
            <img
              src="/hero-stack.png"
              alt="The Foxtheta AI stack: a base layer of interchangeable foundation models, the Foxtheta engineering layer of retrieval, tools, guardrails and evaluation above it, and industry applications for finance, insurance, healthcare, retail, logistics and SaaS rising from it."
              className="hero__image"
              width={1200}
              height={1000}
              fetchPriority="high"
            />

            {/* aria-hidden: the image alt and the legend already name these */}
            {SHOW_TOWER_LABELS && (
              <div className="hero__labels" aria-hidden="true">
                {towerLabels.map((tower, index) => (
                  <span
                    key={tower.id}
                    className="hero__label"
                    style={{
                      left: `${tower.left}%`,
                      top: `${tower.top}%`,
                      "--i": index,
                    }}
                  >
                    {tower.label}
                  </span>
                ))}
              </div>
            )}
          </div>

          <figcaption>
            <ul className="stack-legend">
              {legend.map((row) => (
                <li key={row.id}>
                  <span
                    className={`stack-legend__swatch stack-legend__swatch--${row.swatch}`}
                    aria-hidden="true"
                  />
                  <span>
                    <strong>{row.title}</strong>
                    {row.text}
                  </span>
                </li>
              ))}
            </ul>
          </figcaption>
        </figure>
      </div>
    </section>
  );
}
